# Generated by Django 4.2.6 on 2023-10-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='photo_url',
            field=models.CharField(default='change this', max_length=255),
            preserve_default=False,
        ),
    ]
